"""Export the validated rigid Lara run to deterministic Pingo assembly data."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import struct
import sys
from pathlib import Path

import bpy
from mathutils import Matrix, Vector


PROJECT_ROOT = Path(__file__).resolve().parents[5]
GENERATOR = (
    "blender/anim/bandai_namco/run_normal_001/scripts/"
    "export_pingo_rigid_animation.py"
)
EXPECTED_SEMANTIC_PARTS = 17
EXPECTED_POSITIONS = 300
EXPECTED_TRIANGLES = 526
EXPECTED_TRACKS = 15
EXPECTED_FRAMES = 23
EXPECTED_LOOP_SUCCESSOR_FRAME = 24
EXPECTED_LOOP_CLOSURE_START = 15
POSE_RECORD_SIZE = 12
MAX_SCALE_DEVIATION = 5.0e-5
MAX_DECOMPOSITION_ERROR = 5.0e-5
MAX_SHARED_MATRIX_ERROR = 1.0e-7
MAX_ADJACENT_EULER_STEP = math.radians(45.0)
MAX_QUANTIZED_VERTEX_ERROR = 0.01
MAX_QUANTIZED_ROTATION_ERROR = 0.001
SYMBOL_RE = re.compile(r"^[a-z][a-z0-9_]*$")
QUALIFIED_SOURCE_KEYS = (
    "source_blend",
    "rest_blend",
    "source_texture",
    "model_obj",
    "model_mtl",
    "source_motion",
    "motion_annotation",
    "motion_license",
    "asset_notice",
    "model_provenance",
    "scene_builder",
    "texture_converter",
)

BASIS = Matrix(
    (
        (1.0, 0.0, 0.0, 0.0),
        (0.0, 0.0, 1.0, 0.0),
        (0.0, -1.0, 0.0, 0.0),
        (0.0, 0.0, 0.0, 1.0),
    )
)
BASIS_INVERSE = BASIS.inverted()
BASIS_3X3 = BASIS.to_3x3()


def parse_arguments() -> argparse.Namespace:
    try:
        separator = sys.argv.index("--")
    except ValueError:
        arguments: list[str] = []
    else:
        arguments = sys.argv[separator + 1 :]
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", type=Path, required=True)
    parser.add_argument("--mesh-output", type=Path, required=True)
    parser.add_argument("--pose-output", type=Path, required=True)
    parser.add_argument("--metadata-output", type=Path, required=True)
    return parser.parse_args(arguments)


def project_path(value: str) -> Path:
    path = (PROJECT_ROOT / value).resolve()
    path.relative_to(PROJECT_ROOT.resolve())
    return path


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def matrix_error(left: Matrix, right: Matrix) -> float:
    return max(
        abs(left[row][column] - right[row][column])
        for row in range(4)
        for column in range(4)
    )


def round_half_away_from_zero(value: float) -> int:
    """Match the deterministic rounding used by generated Pingo pose data."""

    magnitude = math.floor(abs(value) + 0.5)
    return -magnitude if value < 0.0 else magnitude


def pingo_rotation(angles: tuple[float, float, float]) -> Matrix:
    return (
        Matrix.Rotation(angles[2], 4, "Z")
        @ Matrix.Rotation(angles[1], 4, "Y")
        @ Matrix.Rotation(angles[0], 4, "X")
    )


def encode_mesh_coordinate(value: float) -> int:
    if not math.isfinite(value) or value < -1.000001 or value > 1.000001:
        raise ValueError(f"mesh coordinate outside normalized range: {value!r}")
    result = round_half_away_from_zero(
        max(-1.0, min(1.0, value)) * 32767.0
    )
    if not -32768 <= result <= 32767:
        raise ValueError(f"mesh coordinate outside signed word: {result}")
    return result


def encode_uv_coordinate(value: float) -> int:
    if not math.isfinite(value) or value < -1.0e-5 or value > 1.00001:
        raise ValueError(f"UV coordinate outside normalized range: {value!r}")
    return round_half_away_from_zero(max(0.0, min(1.0, value)) * 65535.0)


def encode_translation(value: float) -> int:
    if not math.isfinite(value):
        raise ValueError(f"non-finite translation: {value!r}")
    result = round_half_away_from_zero(value * 32767.0 / 256.0)
    if not -32768 <= result <= 32767:
        raise ValueError(f"translation outside Pingo signed-word domain: {result}")
    return result


def encode_angle(value: float) -> int:
    if not math.isfinite(value):
        raise ValueError(f"non-finite Euler angle: {value!r}")
    result = round_half_away_from_zero(value * 32767.0 / (2.0 * math.pi))
    if not -32768 <= result <= 32767:
        raise ValueError(f"Euler angle outside Pingo signed-turn domain: {result}")
    return result


def generated_banner(source: str) -> str:
    return (
        "; =============================================================================\n"
        "; AUTO-GENERATED FILE - DO NOT EDIT\n"
        f"; Generated by: {GENERATOR}\n"
        f"; Generated from: {source}\n"
        "; Edit the generator or its authoritative inputs instead.\n"
        "; =============================================================================\n\n"
    )


def validate_profile(profile: dict[str, object]) -> list[dict[str, object]]:
    required = {
        "name",
        "qualified_blender_version",
        "source_blend",
        "rest_blend",
        "scene",
        "rest_scene",
        "frames",
        "loop_successor_frame",
        "source_texture",
        "model_obj",
        "model_mtl",
        "source_motion",
        "motion_annotation",
        "motion_license",
        "asset_notice",
        "model_provenance",
        "scene_builder",
        "texture_converter",
        "source_sha256",
        "qualified_output_sha256",
        "texture_filename",
        "texture_size",
        "resolution",
        "control_id",
        "texture_bitmap_id",
        "target_bitmap_id",
        "render_notification_token",
        "object_scale",
        "normalization_max_abs",
        "camera_offset",
        "source_rate_hz",
        "default_root_mode",
        "preserves_root_motion",
        "loopable",
        "semantic_meshes",
        "tracks",
    }
    missing = sorted(required - profile.keys())
    if missing:
        raise ValueError(f"animation profile is missing: {', '.join(missing)}")
    if profile["name"] != "anim":
        raise ValueError("animation profile name must be 'anim'")
    if profile["qualified_blender_version"] != "4.0.2":
        raise ValueError("qualified Blender version must be 4.0.2")
    if profile["frames"] != [1, 23]:
        raise ValueError("the qualified loop must export frames 1 through 23")
    if profile["loop_successor_frame"] != EXPECTED_LOOP_SUCCESSOR_FRAME:
        raise ValueError("the qualified loop successor must be source frame 24")
    if profile["loop_successor_frame"] != profile["frames"][1] + 1:
        raise ValueError("the loop successor must immediately follow the final sample")
    if profile["source_rate_hz"] != 30:
        raise ValueError("the qualified clip source rate must be 30 Hz")
    if profile["default_root_mode"] != "controlled":
        raise ValueError("the qualification runtime must use controlled locomotion")
    if profile["preserves_root_motion"] is not True or profile["loopable"] is not True:
        raise ValueError("the qualified clip must preserve root motion and be loopable")
    if float(profile["normalization_max_abs"]) != 0.7247999906539917:
        raise ValueError("qualified whole-character normalization changed")

    source_hashes = profile["source_sha256"]
    if not isinstance(source_hashes, dict) or set(source_hashes) != set(
        QUALIFIED_SOURCE_KEYS
    ):
        raise ValueError("source_sha256 must cover every qualified source exactly")
    for source_key in QUALIFIED_SOURCE_KEYS:
        source = project_path(str(profile[source_key]))
        if not source.is_file():
            raise ValueError(f"missing qualified source: {profile[source_key]}")
        expected_hash = source_hashes[source_key]
        if not isinstance(expected_hash, str) or len(expected_hash) != 64:
            raise ValueError(f"invalid qualified source hash: {source_key}")
        actual_hash = sha256_file(source)
        if actual_hash != expected_hash:
            raise ValueError(
                f"qualified source changed: {profile[source_key]}: "
                f"expected {expected_hash}, found {actual_hash}"
            )

    semantic_meshes = profile["semantic_meshes"]
    if not isinstance(semantic_meshes, list) or len(semantic_meshes) != 17:
        raise ValueError("semantic_meshes must define exactly 17 parts")
    semantic_names: list[str] = []
    for item in semantic_meshes:
        if not isinstance(item, dict) or set(item) != {
            "name",
            "vertices",
            "triangles",
            "driver",
            "geometry_sha256",
        }:
            raise ValueError("invalid semantic mesh contract")
        if not isinstance(item["name"], str) or not isinstance(item["driver"], str):
            raise ValueError("invalid semantic mesh name or driver")
        if not isinstance(item["vertices"], int) or item["vertices"] <= 0:
            raise ValueError("invalid semantic vertex count")
        if not isinstance(item["triangles"], int) or item["triangles"] <= 0:
            raise ValueError("invalid semantic triangle count")
        digest = item["geometry_sha256"]
        if not isinstance(digest, str) or len(digest) != 64:
            raise ValueError("invalid semantic geometry hash")
        semantic_names.append(item["name"])
    if len(semantic_names) != len(set(semantic_names)):
        raise ValueError("semantic mesh names must be unique")
    if sum(int(item["vertices"]) for item in semantic_meshes) != EXPECTED_POSITIONS:
        raise ValueError("semantic vertex counts changed")
    if sum(int(item["triangles"]) for item in semantic_meshes) != EXPECTED_TRIANGLES:
        raise ValueError("semantic triangle counts changed")

    global_ids = [
        int(profile["control_id"]),
        int(profile["texture_bitmap_id"]),
        int(profile["target_bitmap_id"]),
    ]
    if len(set(global_ids)) != len(global_ids):
        raise ValueError("control, texture, and target global IDs must be distinct")
    if any(value <= 0 or value >= 65535 for value in global_ids):
        raise ValueError("global IDs must be in the range 1..65534")
    token = int(profile["render_notification_token"])
    if not 0 <= token <= 65535:
        raise ValueError("render notification token must be a 16-bit value")
    object_scale = int(profile["object_scale"])
    if not 1 <= object_scale <= 65535:
        raise ValueError("object scale must be a nonzero unsigned word")

    for key in ("texture_size", "resolution"):
        values = profile[key]
        if not isinstance(values, list) or len(values) != 2:
            raise ValueError(f"{key} must contain two integers")
        if any(not isinstance(value, int) or value <= 0 for value in values):
            raise ValueError(f"{key} must contain positive integers")
    camera_offset = profile["camera_offset"]
    if not isinstance(camera_offset, list) or len(camera_offset) != 3:
        raise ValueError("camera_offset must contain three signed words")
    if any(not isinstance(value, int) or not -32768 <= value <= 32767 for value in camera_offset):
        raise ValueError("camera_offset must contain signed 16-bit values")

    tracks = profile["tracks"]
    if not isinstance(tracks, list) or len(tracks) != EXPECTED_TRACKS:
        raise ValueError(f"profile must define exactly {EXPECTED_TRACKS} tracks")
    names: list[str] = []
    sources: list[str] = []
    validated: list[dict[str, object]] = []
    for track in tracks:
        if not isinstance(track, dict):
            raise ValueError("each track must be an object")
        if set(track) != {"name", "sources", "driver"}:
            raise ValueError(f"unexpected track fields: {sorted(track)}")
        name = track["name"]
        driver = track["driver"]
        track_sources = track["sources"]
        if not isinstance(name, str) or not SYMBOL_RE.fullmatch(name):
            raise ValueError(f"assembly-unsafe track name: {name!r}")
        if not isinstance(driver, str) or not driver:
            raise ValueError(f"invalid driver for {name}")
        if not isinstance(track_sources, list) or not track_sources:
            raise ValueError(f"{name} needs at least one source mesh")
        if any(not isinstance(value, str) or not value for value in track_sources):
            raise ValueError(f"invalid source list for {name}")
        if driver not in track_sources and name != "pelvis_bundle":
            raise ValueError(f"{name} driver must be its source mesh")
        names.append(name)
        sources.extend(track_sources)
        validated.append(track)
    if len(names) != len(set(names)):
        raise ValueError("track names must be unique")
    if len(sources) != EXPECTED_SEMANTIC_PARTS or len(sources) != len(set(sources)):
        raise ValueError("tracks must cover exactly 17 unique semantic meshes")
    if sources != semantic_names:
        raise ValueError("track sources must match semantic_meshes in exact order")
    expected_drivers = {
        str(source): str(track["driver"])
        for track in tracks
        for source in track["sources"]
    }
    if any(item["driver"] != expected_drivers[item["name"]] for item in semantic_meshes):
        raise ValueError("semantic mesh drivers do not match the track contract")
    first = validated[0]
    if first != {
        "name": "pelvis_bundle",
        "sources": ["pelvis", "holster.l", "holster.r"],
        "driver": "pelvis",
    }:
        raise ValueError("track zero must be the exact pelvis/holster bundle")
    return validated


def semantic_mesh_geometry_sha256(mesh: bpy.types.Mesh) -> str:
    """Hash corrected local geometry, winding, topology, and per-corner UVs."""

    uv_layer = mesh.uv_layers.get("UVMap")
    if uv_layer is None:
        raise ValueError(f"mesh has no UVMap layer: {mesh.name}")
    if any(len(polygon.vertices) != 3 for polygon in mesh.polygons):
        raise ValueError(f"mesh is not triangulated: {mesh.name}")
    digest = hashlib.sha256()
    digest.update(b"pingoasm.rigid_mesh.geometry.v1\0")
    digest.update(struct.pack("<II", len(mesh.vertices), len(mesh.polygons)))
    for vertex in mesh.vertices:
        digest.update(struct.pack("<3f", *vertex.co))
    for polygon in mesh.polygons:
        digest.update(struct.pack("<3I", *polygon.vertices))
        for loop_index in polygon.loop_indices:
            digest.update(struct.pack("<2f", *uv_layer.data[loop_index].uv))
    return digest.hexdigest()


def validate_shared_material(
    objects: list[bpy.types.Object],
    source_texture: Path,
) -> None:
    materials: list[bpy.types.Material] = []
    for obj in objects:
        mesh = obj.data
        if len(mesh.uv_layers) != 1 or mesh.uv_layers.active is None:
            raise ValueError(f"{obj.name} must have one active UV layer")
        if mesh.uv_layers.active.name != "UVMap":
            raise ValueError(f"{obj.name} must use active UVMap")
        if len(obj.material_slots) != 1 or obj.material_slots[0].link != "DATA":
            raise ValueError(f"{obj.name} must have one data-linked material slot")
        if len(mesh.materials) != 1 or mesh.materials[0] is None:
            raise ValueError(f"{obj.name} must have one mesh material")
        material = mesh.materials[0]
        if material.name != "tile0" or obj.material_slots[0].material != material:
            raise ValueError(f"{obj.name} must use material tile0 without override")
        materials.append(material)

    shared = materials[0]
    if any(material != shared for material in materials[1:]):
        raise ValueError("all semantic meshes must share one tile0 material")
    if not shared.use_nodes or shared.node_tree is None:
        raise ValueError("tile0 must use nodes")
    if getattr(shared, "blend_method", "OPAQUE") != "OPAQUE":
        raise ValueError("tile0 must be opaque")
    image_nodes = [node for node in shared.node_tree.nodes if node.type == "TEX_IMAGE"]
    if len(image_nodes) != 1 or image_nodes[0].image is None:
        raise ValueError("tile0 must contain exactly one bound image texture node")
    image = image_nodes[0].image
    if image.name != "Lara.png" or image.source != "FILE" or image.packed_file is not None:
        raise ValueError("tile0 must bind the unpacked Lara.png file image")
    if image.filepath != "//../source/Lara.png":
        raise ValueError(f"unexpected Lara image path: {image.filepath!r}")
    resolved_image = Path(bpy.path.abspath(image.filepath)).resolve()
    if resolved_image != source_texture.resolve():
        raise ValueError(f"tile0 resolves to the wrong texture: {resolved_image}")
    if tuple(int(value) for value in image.size) != (256, 184):
        raise ValueError(f"unexpected Lara image dimensions: {tuple(image.size)}")

    principled = [node for node in shared.node_tree.nodes if node.type == "BSDF_PRINCIPLED"]
    outputs = [node for node in shared.node_tree.nodes if node.type == "OUTPUT_MATERIAL"]
    if len(principled) != 1 or len(outputs) != 1:
        raise ValueError("tile0 must have one Principled BSDF and material output")
    links = shared.node_tree.links
    if not any(
        link.from_node == image_nodes[0]
        and link.from_socket.name == "Color"
        and link.to_node == principled[0]
        and link.to_socket.name == "Base Color"
        for link in links
    ):
        raise ValueError("tile0 image Color must feed Principled Base Color")
    if not any(
        link.from_node == principled[0]
        and link.from_socket.name == "BSDF"
        and link.to_node == outputs[0]
        and link.to_socket.name == "Surface"
        for link in links
    ):
        raise ValueError("tile0 Principled BSDF must feed material Surface")


def collect_semantic_mesh_contract(
    scene: bpy.types.Scene,
    semantic_meshes: list[dict[str, object]],
    source_texture: Path,
    *,
    name_prefix: str,
) -> dict[str, dict[str, object]]:
    objects: list[bpy.types.Object] = []
    results: dict[str, dict[str, object]] = {}
    for expected in semantic_meshes:
        source_name = str(expected["name"])
        object_name = name_prefix + source_name
        obj = scene.objects.get(object_name)
        if obj is None or obj.type != "MESH":
            raise ValueError(f"missing semantic mesh object: {object_name}")
        if obj.data.name != f"lara_{source_name}":
            raise ValueError(
                f"unexpected mesh datablock for {object_name}: {obj.data.name}"
            )
        if obj.get("driven_by_bone") != expected["driver"]:
            raise ValueError(
                f"unexpected bone driver for {object_name}: "
                f"{obj.get('driven_by_bone')!r}"
            )
        geometry_hash = semantic_mesh_geometry_sha256(obj.data)
        actual = {
            "name": source_name,
            "positions": len(obj.data.vertices),
            "triangles": len(obj.data.polygons),
            "driver": str(obj.get("driven_by_bone")),
            "geometry_sha256": geometry_hash,
        }
        qualified = {
            "name": source_name,
            "positions": int(expected["vertices"]),
            "triangles": int(expected["triangles"]),
            "driver": str(expected["driver"]),
            "geometry_sha256": str(expected["geometry_sha256"]),
        }
        if actual != qualified:
            raise ValueError(
                f"qualified semantic geometry changed for {object_name}: "
                f"expected {qualified!r}, found {actual!r}"
            )
        objects.append(obj)
        results[source_name] = actual
    validate_shared_material(objects, source_texture)
    return results


def extract_meshes(
    tracks: list[dict[str, object]],
    normalization: float,
) -> tuple[list[dict[str, object]], int, int]:
    exported: list[dict[str, object]] = []
    total_positions = 0
    total_triangles = 0
    for track_index, track in enumerate(tracks, start=1):
        positions: list[tuple[int, int, int]] = []
        local_points: list[Vector] = []
        faces: list[tuple[int, int, int]] = []
        uv_words: list[tuple[int, int]] = []
        uv_lookup: dict[tuple[int, int], int] = {}
        uv_indices: list[tuple[int, int, int]] = []
        source_counts: list[dict[str, int | str]] = []

        for source_name in track["sources"]:
            obj = bpy.data.objects.get(str(source_name))
            if obj is None or obj.type != "MESH":
                raise ValueError(f"missing source mesh object: {source_name}")
            mesh = obj.data
            if mesh.uv_layers.active is None:
                raise ValueError(f"source mesh has no active UV layer: {source_name}")
            if mesh.uv_layers.active.name != "UVMap":
                raise ValueError(
                    f"source mesh uses unexpected UV layer: {source_name}: "
                    f"{mesh.uv_layers.active.name}"
                )
            material_names = [material.name for material in mesh.materials]
            if material_names != ["tile0"]:
                raise ValueError(
                    f"source mesh uses unexpected materials: {source_name}: "
                    f"{material_names!r}"
                )
            if any(len(polygon.vertices) != 3 for polygon in mesh.polygons):
                raise ValueError(f"source mesh is not triangulated: {source_name}")
            mesh.calc_loop_triangles()
            vertex_base = len(positions)
            for vertex in mesh.vertices:
                converted = BASIS_3X3 @ vertex.co
                local_points.append(converted.copy())
                positions.append(
                    tuple(
                        encode_mesh_coordinate(component / normalization)
                        for component in converted
                    )
                )

            triangle_count = 0
            for triangle in mesh.loop_triangles:
                faces.append(
                    tuple(vertex_base + int(index) for index in triangle.vertices)
                )
                triangle_uvs: list[int] = []
                for loop_index in triangle.loops:
                    uv = mesh.uv_layers.active.data[loop_index].uv
                    encoded = (
                        encode_uv_coordinate(float(uv.x)),
                        encode_uv_coordinate(float(uv.y)),
                    )
                    uv_index = uv_lookup.get(encoded)
                    if uv_index is None:
                        uv_index = len(uv_words)
                        uv_lookup[encoded] = uv_index
                        uv_words.append(encoded)
                    triangle_uvs.append(uv_index)
                uv_indices.append(tuple(triangle_uvs))
                triangle_count += 1
            source_counts.append(
                {
                    "name": str(source_name),
                    "positions": len(mesh.vertices),
                    "triangles": triangle_count,
                }
            )

        if len(faces) != len(uv_indices):
            raise ValueError(f"position/UV index mismatch for {track['name']}")
        if any(index < 0 or index >= len(positions) for face in faces for index in face):
            raise ValueError(f"position index outside mesh for {track['name']}")
        if any(index < 0 or index >= len(uv_words) for face in uv_indices for index in face):
            raise ValueError(f"UV index outside mesh for {track['name']}")
        if max(len(positions), len(uv_words), len(faces) * 3) > 65535:
            raise ValueError(f"Pingo count exceeds 16-bit range for {track['name']}")

        total_positions += len(positions)
        total_triangles += len(faces)
        exported.append(
            {
                "index": track_index,
                "name": track["name"],
                "driver": track["driver"],
                "sources": track["sources"],
                "source_counts": source_counts,
                "positions": positions,
                "local_points": local_points,
                "faces": faces,
                "uv_words": uv_words,
                "uv_indices": uv_indices,
            }
        )
    return exported, total_positions, total_triangles


def extract_poses(
    scene: bpy.types.Scene,
    tracks: list[dict[str, object]],
    meshes: list[dict[str, object]],
    frame_start: int,
    frame_end: int,
    normalization: float,
    object_scale_word: int,
) -> tuple[list[list[tuple[int, int, int, int, int, int]]], dict[str, object]]:
    object_scale = object_scale_word / 256.0
    previous_eulers: dict[str, object] = {str(track["name"]): None for track in tracks}
    previous_angles: dict[str, tuple[float, float, float] | None] = {
        str(track["name"]): None for track in tracks
    }
    frames: list[list[tuple[int, int, int, int, int, int]]] = []
    scale_deviation_max = 0.0
    decomposition_error_max = 0.0
    shared_matrix_error_max = 0.0
    quantized_rotation_error_max = 0.0
    quantized_vertex_error_max = 0.0
    adjacent_euler_step_max = [0.0, 0.0, 0.0]
    angle_min = [math.inf, math.inf, math.inf]
    angle_max = [-math.inf, -math.inf, -math.inf]
    translation_word_min = [32767, 32767, 32767]
    translation_word_max = [-32768, -32768, -32768]
    root_locations: dict[int, Vector] = {}

    for frame in range(frame_start, frame_end + 1):
        scene.frame_set(frame)
        bpy.context.view_layer.update()
        depsgraph = bpy.context.evaluated_depsgraph_get()
        evaluated_matrices = {
            str(source): bpy.data.objects[str(source)]
            .evaluated_get(depsgraph)
            .matrix_world.copy()
            for track in tracks
            for source in track["sources"]
        }
        pelvis_matrix = evaluated_matrices["pelvis"]
        for holster in ("holster.l", "holster.r"):
            shared_matrix_error_max = max(
                shared_matrix_error_max,
                matrix_error(pelvis_matrix, evaluated_matrices[holster]),
            )

        frame_records: list[tuple[int, int, int, int, int, int]] = []
        for track, mesh in zip(tracks, meshes, strict=True):
            track_name = str(track["name"])
            driver = str(track["driver"])
            converted = BASIS @ evaluated_matrices[driver] @ BASIS_INVERSE
            location, quaternion, scale = converted.decompose()
            quaternion.normalize()
            scale_deviation_max = max(
                scale_deviation_max,
                abs(scale.x - 1.0),
                abs(scale.y - 1.0),
                abs(scale.z - 1.0),
            )
            rigid = Matrix.Translation(location) @ quaternion.to_matrix().to_4x4()
            decomposition_error_max = max(
                decomposition_error_max,
                matrix_error(converted, rigid),
            )

            previous = previous_eulers[track_name]
            if previous is None:
                euler = quaternion.to_euler("XYZ")
            else:
                euler = quaternion.to_euler("XYZ", previous)
            previous_eulers[track_name] = euler.copy()
            angles = (float(euler.x), float(euler.y), float(euler.z))
            prior_angles = previous_angles[track_name]
            if prior_angles is not None:
                for axis in range(3):
                    adjacent_euler_step_max[axis] = max(
                        adjacent_euler_step_max[axis],
                        abs(angles[axis] - prior_angles[axis]),
                    )
            previous_angles[track_name] = angles

            translation = tuple(
                float(component) * object_scale / normalization
                for component in location
            )
            translation_words = tuple(encode_translation(value) for value in translation)
            angle_words = tuple(encode_angle(value) for value in angles)
            record = (*translation_words, *angle_words)
            frame_records.append(record)
            for axis in range(3):
                angle_min[axis] = min(angle_min[axis], angles[axis])
                angle_max[axis] = max(angle_max[axis], angles[axis])
                translation_word_min[axis] = min(
                    translation_word_min[axis], translation_words[axis]
                )
                translation_word_max[axis] = max(
                    translation_word_max[axis], translation_words[axis]
                )

            quantized_translation = Vector(
                tuple(value * 256.0 / 32767.0 for value in translation_words)
            )
            quantized_angles = tuple(
                value * (2.0 * math.pi) / 32767.0 for value in angle_words
            )
            quantized_rotation = pingo_rotation(quantized_angles)
            quantized_rotation_error_max = max(
                quantized_rotation_error_max,
                matrix_error(quaternion.to_matrix().to_4x4(), quantized_rotation),
            )
            positions = mesh["positions"]
            local_points = mesh["local_points"]
            for position, local_point in zip(positions, local_points, strict=True):
                exact_source = converted @ Vector((*local_point, 1.0))
                exact = exact_source.xyz * (object_scale / normalization)
                quantized_local = Vector(
                    tuple(component / 32767.0 for component in position)
                )
                quantized = (
                    quantized_translation
                    + (quantized_rotation @ quantized_local) * object_scale
                )
                quantized_vertex_error_max = max(
                    quantized_vertex_error_max,
                    (exact - quantized).length,
                )

            if track_name == "pelvis_bundle":
                root_locations[frame] = Vector(translation)
        frames.append(frame_records)

    if scale_deviation_max > MAX_SCALE_DEVIATION:
        raise ValueError(f"keyed scale residue too large: {scale_deviation_max}")
    if decomposition_error_max > MAX_DECOMPOSITION_ERROR:
        raise ValueError(f"rigid decomposition error too large: {decomposition_error_max}")
    if shared_matrix_error_max > MAX_SHARED_MATRIX_ERROR:
        raise ValueError(f"pelvis/holster matrices diverged: {shared_matrix_error_max}")
    if max(adjacent_euler_step_max) > MAX_ADJACENT_EULER_STEP:
        raise ValueError(
            "continuous Euler step exceeded 45 degrees: "
            + repr([math.degrees(value) for value in adjacent_euler_step_max])
        )
    if quantized_vertex_error_max > MAX_QUANTIZED_VERTEX_ERROR:
        raise ValueError(
            f"quantized transformed-vertex error too large: {quantized_vertex_error_max}"
        )
    if quantized_rotation_error_max > MAX_QUANTIZED_ROTATION_ERROR:
        raise ValueError(
            f"quantized rotation coefficient error too large: "
            f"{quantized_rotation_error_max}"
        )

    root_delta = root_locations[frame_end] - root_locations[frame_start]
    metrics: dict[str, object] = {
        "scale_deviation_max": scale_deviation_max,
        "decomposition_coefficient_error_max": decomposition_error_max,
        "pelvis_holster_matrix_error_max": shared_matrix_error_max,
        "quantized_rotation_coefficient_error_max": quantized_rotation_error_max,
        "quantized_transformed_vertex_error_max": quantized_vertex_error_max,
        "continuous_euler_degrees_min": [math.degrees(value) for value in angle_min],
        "continuous_euler_degrees_max": [math.degrees(value) for value in angle_max],
        "adjacent_euler_step_degrees_max": [
            math.degrees(value) for value in adjacent_euler_step_max
        ],
        "translation_word_min": translation_word_min,
        "translation_word_max": translation_word_max,
        "root_delta_command_units": list(root_delta),
    }
    return frames, metrics


def analyze_loop(
    sampled_frames: list[list[tuple[int, int, int, int, int, int]]],
    frame_start: int,
    frame_end: int,
    successor_frame: int,
) -> dict[str, object]:
    """Measure the stored cycle against its non-stored periodic successor."""

    if len(sampled_frames) != frame_end - frame_start + 2:
        raise ValueError("loop sampling must include one non-stored successor")
    if successor_frame != frame_end + 1:
        raise ValueError("loop successor is not adjacent to the stored cycle")
    selected = sampled_frames[:-1]
    first = selected[0]
    second = selected[1]
    previous = selected[-1]
    successor = sampled_frames[-1]
    root_words = [frame[0][2] for frame in sampled_frames]
    forward_steps = [right - left for left, right in zip(root_words, root_words[1:])]
    if len(forward_steps) != len(selected) or any(step <= 0 for step in forward_steps):
        raise ValueError(f"loop root motion is not strictly forward: {forward_steps!r}")
    cycle_forward = root_words[-1] - root_words[0]
    loop_forward_step = forward_steps[-1]
    nominal_forward_step = round_half_away_from_zero(
        cycle_forward / len(selected)
    )

    def normalized_translation(frame, track):
        record = frame[track]
        return Vector((record[0], record[1], record[2] - frame[0][2]))

    def rotation(record):
        angles = tuple(
            value * (2.0 * math.pi) / 32767.0 for value in record[3:]
        )
        return pingo_rotation(angles).to_3x3()

    def coefficient_error(left, right):
        return max(
            abs(left[row][column] - right[row][column])
            for row in range(3)
            for column in range(3)
        )

    endpoint_translation_errors = []
    endpoint_rotation_errors = []
    endpoint_rotation_angles = []
    velocity_translation_errors = []
    velocity_rotation_errors = []
    velocity_rotation_angles = []
    for track in range(len(first)):
        first_translation = normalized_translation(first, track)
        second_translation = normalized_translation(second, track)
        previous_translation = normalized_translation(previous, track)
        successor_translation = normalized_translation(successor, track)
        endpoint_translation_errors.append(
            max(abs(value) for value in successor_translation - first_translation)
        )
        velocity_translation_errors.append(
            max(
                abs(value)
                for value in (
                    successor_translation - previous_translation
                    - (second_translation - first_translation)
                )
            )
        )

        first_rotation = rotation(first[track])
        second_rotation = rotation(second[track])
        previous_rotation = rotation(previous[track])
        successor_rotation = rotation(successor[track])
        endpoint_rotation_errors.append(
            coefficient_error(first_rotation, successor_rotation)
        )
        endpoint_rotation_angles.append(
            math.degrees(
                (first_rotation.transposed() @ successor_rotation)
                .to_quaternion()
                .angle
            )
        )
        first_step = first_rotation.transposed() @ second_rotation
        seam_step = previous_rotation.transposed() @ successor_rotation
        velocity_rotation_errors.append(coefficient_error(first_step, seam_step))
        velocity_rotation_angles.append(
            math.degrees((first_step.transposed() @ seam_step).to_quaternion().angle)
        )

    return {
        "loop_successor_frame": successor_frame,
        "loop_forward_step_command_units": loop_forward_step,
        "loop_cycle_forward_command_units": cycle_forward,
        "loop_nominal_forward_step_command_units": nominal_forward_step,
        "loop_root_forward_steps_command_units": forward_steps,
        "loop_endpoint_translation_word_error_max": max(
            endpoint_translation_errors
        ),
        "loop_endpoint_rotation_coefficient_error_max": max(
            endpoint_rotation_errors
        ),
        "loop_endpoint_rotation_degrees_max": max(endpoint_rotation_angles),
        "loop_velocity_translation_word_error_max": max(
            velocity_translation_errors
        ),
        "loop_velocity_rotation_coefficient_error_max": max(
            velocity_rotation_errors
        ),
        "loop_velocity_rotation_degrees_max": max(velocity_rotation_angles),
    }


def mesh_include_text(
    source: str,
    profile: dict[str, object],
    meshes: list[dict[str, object]],
) -> str:
    texture_width, texture_height = profile["texture_size"]
    texture_size = texture_width * texture_height
    lines = [generated_banner(source)]
    lines.extend(
        [
            f"lara_texture_width: equ {texture_width}\n",
            f"lara_texture_height: equ {texture_height}\n",
            f"lara_texture_size: equ {texture_size}\n",
            f"lara_mesh_count: equ {len(meshes)}\n\n",
            "; Upload all mesh-owned arrays to the selected Pingo control.\n",
            "lara_upload_meshes:\n",
        ]
    )
    for mesh in meshes:
        prefix = f"lara_{mesh['name']}"
        lines.extend(
            [
                f"    SV sid,{prefix}_mid,{prefix}_vertices,{prefix}_vertices_n\n",
                f"    SMVI sid,{prefix}_mid,{prefix}_vertex_indices,{prefix}_indices_n\n",
                f"    STC sid,{prefix}_mid,{prefix}_uvs,{prefix}_uvs_n\n",
                f"    STCI sid,{prefix}_mid,{prefix}_uv_indices,{prefix}_indices_n\n",
            ]
        )
    lines.append("    ret\n\n")

    for mesh in meshes:
        prefix = f"lara_{mesh['name']}"
        lines.extend(
            [
                f"; Track {mesh['index'] - 1}: {mesh['name']} from "
                f"{', '.join(mesh['sources'])}.\n",
                f"{prefix}_mid: equ {mesh['index']}\n",
                f"{prefix}_oid: equ {mesh['index']}\n",
                f"{prefix}_vertices_n: equ {len(mesh['positions'])}\n",
                f"{prefix}_indices_n: equ {len(mesh['faces']) * 3}\n",
                f"{prefix}_uvs_n: equ {len(mesh['uv_words'])}\n\n",
                f"{prefix}_vertices:\n",
            ]
        )
        lines.extend(
            f"    dw {x},{y},{z}\n" for x, y, z in mesh["positions"]
        )
        lines.extend(["\n", f"{prefix}_vertex_indices:\n"])
        lines.extend(f"    dw {a},{b},{c}\n" for a, b, c in mesh["faces"])
        lines.extend(["\n", f"{prefix}_uvs:\n"])
        lines.extend(f"    dw {u},{v}\n" for u, v in mesh["uv_words"])
        lines.extend(["\n", f"{prefix}_uv_indices:\n"])
        lines.extend(f"    dw {a},{b},{c}\n" for a, b, c in mesh["uv_indices"])
        lines.append("\n")
    lines.append(f"lara_texture: db \"{profile['texture_filename']}\",0\n")
    return "".join(lines)


def pose_include_text(
    source: str,
    profile: dict[str, object],
    meshes: list[dict[str, object]],
    frames: list[list[tuple[int, int, int, int, int, int]]],
    normalization: float,
    loop_metrics: dict[str, object],
) -> str:
    width, height = profile["resolution"]
    camera_x, camera_y, camera_z = profile["camera_offset"]
    frame_size = len(meshes) * POSE_RECORD_SIZE
    lines = [generated_banner(source)]
    lines.extend(
        [
            f"sid: equ {profile['control_id']}\n",
            f"lara_texture_bmid: equ {profile['texture_bitmap_id']}\n",
            f"tgtbmid: equ {profile['target_bitmap_id']}\n",
            f"viewport_width: equ {width}\n",
            f"viewport_height: equ {height}\n",
            f"lara_object_scale: equ {profile['object_scale']}\n",
            f"lara_camera_offset_x: equ {camera_x}\n",
            f"lara_camera_offset_y: equ {camera_y}\n",
            f"lara_camera_offset_z: equ {camera_z}\n",
            f"lara_source_rate_hz: equ {profile['source_rate_hz']}\n",
            f"lara_pose_frame_start: equ {profile['frames'][0]}\n",
            f"lara_pose_frame_end: equ {profile['frames'][1]}\n",
            f"lara_loop_successor_frame: equ {profile['loop_successor_frame']}\n",
            f"lara_pose_frame_count: equ {len(frames)}\n",
            "lara_loop_forward_step: equ "
            f"{loop_metrics['loop_forward_step_command_units']}\n",
            "lara_cycle_forward_distance: equ "
            f"{loop_metrics['loop_cycle_forward_command_units']}\n",
            "lara_nominal_forward_step: equ "
            f"{loop_metrics['loop_nominal_forward_step_command_units']}\n",
            f"lara_track_count: equ {len(meshes)}\n",
            f"lara_pose_record_size: equ {POSE_RECORD_SIZE}\n",
            f"lara_pose_frame_size: equ {frame_size}\n",
            f"lara_pose_table_size: equ {len(frames) * frame_size}\n",
            f"; Whole-character Blender normalization: {normalization:.17g}\n\n",
            "; Four-word p3d initialization tuples in stable track order.\n",
            "lara_object_ids:\n",
        ]
    )
    for mesh in meshes:
        prefix = f"lara_{mesh['name']}"
        lines.append(
            f"    dw sid,{prefix}_oid,{prefix}_mid,lara_texture_bmid"
            f" ; {mesh['name']}\n"
        )
    lines.extend(
        [
            "\n",
            "; Frame-major records: tx,ty,tz,rx,ry,rz as signed words.\n",
            "lara_pose_samples:\n",
        ]
    )
    frame_start = int(profile["frames"][0])
    for frame_index, records in enumerate(frames):
        lines.append(f"; Source frame {frame_start + frame_index}\n")
        for mesh, record in zip(meshes, records, strict=True):
            lines.append(
                "    dw " + ",".join(str(value) for value in record)
                + f" ; {mesh['name']}\n"
            )
    return "".join(lines)


def export(arguments: argparse.Namespace) -> None:
    profile_path = arguments.profile.resolve()
    profile_path.relative_to(PROJECT_ROOT.resolve())
    profile = json.loads(profile_path.read_text(encoding="utf-8"))
    tracks = validate_profile(profile)
    source_blend = project_path(str(profile["source_blend"]))
    rest_blend = project_path(str(profile["rest_blend"]))
    source_texture = project_path(str(profile["source_texture"]))
    if bpy.app.version_string != profile["qualified_blender_version"]:
        raise ValueError(
            f"Blender {profile['qualified_blender_version']} is required, "
            f"found {bpy.app.version_string}"
        )

    semantic_meshes = profile["semantic_meshes"]
    bpy.ops.wm.open_mainfile(filepath=str(rest_blend))
    rest_scene = bpy.data.scenes.get(str(profile["rest_scene"]))
    if rest_scene is None:
        raise ValueError(f"missing rest scene: {profile['rest_scene']}")
    rest_contract = collect_semantic_mesh_contract(
        rest_scene,
        semantic_meshes,
        source_texture,
        name_prefix="REST_",
    )

    bpy.ops.wm.open_mainfile(filepath=str(source_blend))

    scene = bpy.data.scenes.get(str(profile["scene"]))
    if scene is None:
        raise ValueError(f"missing scene: {profile['scene']}")
    if bpy.context.window is not None:
        bpy.context.window.scene = scene
    frame_start, frame_end = (int(value) for value in profile["frames"])
    loop_successor_frame = int(profile["loop_successor_frame"])
    if (scene.frame_start, scene.frame_end) != (frame_start, frame_end):
        raise ValueError(
            f"scene frame range is {scene.frame_start}..{scene.frame_end}, "
            f"profile requires {frame_start}..{frame_end}"
        )
    expected_scene_properties = {
        "loop_frame_start": frame_start,
        "loop_frame_end": frame_end,
        "loop_successor_frame": loop_successor_frame,
        "loop_closure_start": EXPECTED_LOOP_CLOSURE_START,
        "loop_closure_space": "pose-bone local quaternion/location/scale",
        "loop_closure_order": "discrete C1",
        "motion_source_frame_start": 1,
        "motion_source_frame_end": 68,
    }
    for key, expected in expected_scene_properties.items():
        if scene.get(key) != expected:
            raise ValueError(
                f"unexpected loop scene property {key}: "
                f"expected {expected!r}, found {scene.get(key)!r}"
            )
    if (
        scene.render.fps != int(profile["source_rate_hz"])
        or scene.render.fps_base != 1.0
    ):
        raise ValueError(
            f"scene rate is {scene.render.fps}/{scene.render.fps_base}, profile requires "
            f"{profile['source_rate_hz']}"
        )

    source_names = [str(source) for track in tracks for source in track["sources"]]
    run_contract = collect_semantic_mesh_contract(
        scene,
        semantic_meshes,
        source_texture,
        name_prefix="",
    )
    if rest_contract.keys() != run_contract.keys():
        raise ValueError("rest/running semantic mesh inventories differ")
    for source_name in source_names:
        if rest_contract[source_name] != run_contract[source_name]:
            raise ValueError(f"rest/running geometry differs for {source_name}")

    source_objects = []
    for name in source_names:
        obj = bpy.data.objects.get(name)
        if obj is None or obj.type != "MESH":
            raise ValueError(f"missing semantic mesh: {name}")
        source_objects.append(obj)
    normalization = max(
        abs(component)
        for obj in source_objects
        for vertex in obj.data.vertices
        for component in (BASIS_3X3 @ vertex.co)
    )
    if not math.isfinite(normalization) or normalization <= 0.0:
        raise ValueError(f"invalid whole-character normalization: {normalization}")
    if normalization != float(profile["normalization_max_abs"]):
        raise ValueError(
            f"qualified normalization changed: expected "
            f"{profile['normalization_max_abs']}, found {normalization}"
        )

    meshes, total_positions, total_triangles = extract_meshes(tracks, normalization)
    for mesh in meshes:
        for source_count in mesh["source_counts"]:
            source_name = str(source_count["name"])
            source_count["driver"] = run_contract[source_name]["driver"]
            source_count["rest_geometry_sha256"] = rest_contract[source_name][
                "geometry_sha256"
            ]
            source_count["run_geometry_sha256"] = run_contract[source_name][
                "geometry_sha256"
            ]
    if total_positions != EXPECTED_POSITIONS:
        raise ValueError(
            f"expected {EXPECTED_POSITIONS} positions, found {total_positions}"
        )
    if total_triangles != EXPECTED_TRIANGLES:
        raise ValueError(
            f"expected {EXPECTED_TRIANGLES} triangles, found {total_triangles}"
        )
    sampled_frames, metrics = extract_poses(
        scene,
        tracks,
        meshes,
        frame_start,
        loop_successor_frame,
        normalization,
        int(profile["object_scale"]),
    )
    frames = sampled_frames[:-1]
    if len(frames) != EXPECTED_FRAMES:
        raise ValueError(f"expected {EXPECTED_FRAMES} frames, found {len(frames)}")
    loop_metrics = analyze_loop(
        sampled_frames,
        frame_start,
        frame_end,
        loop_successor_frame,
    )
    if loop_metrics["loop_endpoint_translation_word_error_max"] > 1.0:
        raise ValueError("loop endpoint translation exceeds one quantization count")
    if loop_metrics["loop_endpoint_rotation_degrees_max"] > 0.01:
        raise ValueError("loop endpoint rotation did not close")
    # Discrete local-bone C1 is exact. Hierarchy composition leaves a small,
    # measured finite-step world-space residual; gate it as a diagnostic rather
    # than breaking the coherent skeleton with independent object corrections.
    if loop_metrics["loop_velocity_translation_word_error_max"] > 24.0:
        raise ValueError("loop world-translation velocity residual changed")
    if loop_metrics["loop_velocity_rotation_degrees_max"] > 2.0:
        raise ValueError("loop world-rotation velocity residual changed")
    metrics.update(loop_metrics)

    source_label = str(profile["source_blend"])
    mesh_text = mesh_include_text(source_label, profile, meshes)
    pose_text = pose_include_text(
        source_label,
        profile,
        meshes,
        frames,
        normalization,
        loop_metrics,
    )
    for path in (arguments.mesh_output, arguments.pose_output, arguments.metadata_output):
        path.parent.mkdir(parents=True, exist_ok=True)
    arguments.mesh_output.write_text(mesh_text, encoding="utf-8", newline="\n")
    arguments.pose_output.write_text(pose_text, encoding="utf-8", newline="\n")

    metadata = {
        "schema_version": 2,
        "generator": GENERATOR,
        "source": {
            "inputs": {
                key: {
                    "path": str(profile[key]),
                    "sha256": str(profile["source_sha256"][key]),
                }
                for key in QUALIFIED_SOURCE_KEYS
            },
            "profile": {
                "path": profile_path.relative_to(PROJECT_ROOT).as_posix(),
                "sha256": sha256_file(profile_path),
            },
            "exporter_sha256": sha256_file(Path(__file__).resolve()),
            "blender_version": bpy.app.version_string,
        },
        "contract": {
            "basis": {"pingo_xyz": ["blender_x", "blender_z", "-blender_y"]},
            "normalization_max_abs": normalization,
            "object_scale_word": int(profile["object_scale"]),
            "object_scale": int(profile["object_scale"]) / 256.0,
            "frame_start": frame_start,
            "frame_end": frame_end,
            "frame_count": len(frames),
            "loop_successor_frame": loop_successor_frame,
            "loop_closure_start": EXPECTED_LOOP_CLOSURE_START,
            "loop_closure_space": str(scene["loop_closure_space"]),
            "loop_closure_order": str(scene["loop_closure_order"]),
            "loop_forward_step_command_units": loop_metrics[
                "loop_forward_step_command_units"
            ],
            "cycle_forward_command_units": loop_metrics[
                "loop_cycle_forward_command_units"
            ],
            "nominal_forward_step_command_units": loop_metrics[
                "loop_nominal_forward_step_command_units"
            ],
            "source_rate_hz": int(profile["source_rate_hz"]),
            "track_count": len(meshes),
            "pose_record_bytes": POSE_RECORD_SIZE,
            "pose_table_bytes": len(frames) * len(meshes) * POSE_RECORD_SIZE,
            "record_fields": ["tx", "ty", "tz", "rx", "ry", "rz"],
            "preserves_root_motion": bool(profile["preserves_root_motion"]),
            "loopable": bool(profile["loopable"]),
        },
        "geometry": {
            "semantic_parts": EXPECTED_SEMANTIC_PARTS,
            "runtime_meshes": len(meshes),
            "positions": total_positions,
            "triangles": total_triangles,
            "tracks": [
                {
                    "index": mesh["index"] - 1,
                    "mesh_id": mesh["index"],
                    "object_id": mesh["index"],
                    "name": mesh["name"],
                    "sources": mesh["sources"],
                    "driver": mesh["driver"],
                    "positions": len(mesh["positions"]),
                    "triangles": len(mesh["faces"]),
                    "uvs": len(mesh["uv_words"]),
                    "source_counts": mesh["source_counts"],
                }
                for mesh in meshes
            ],
        },
        "validation": metrics,
        "outputs": {
            "lara-meshes.inc": sha256_bytes(mesh_text.encode("utf-8")),
            "lara-poses.inc": sha256_bytes(pose_text.encode("utf-8")),
        },
    }
    arguments.metadata_output.write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(
        "PINGO_ANIM_EXPORT="
        + json.dumps(
            {
                "frames": len(frames),
                "tracks": len(meshes),
                "positions": total_positions,
                "triangles": total_triangles,
                "pose_bytes": len(frames) * len(meshes) * POSE_RECORD_SIZE,
                "quantized_vertex_error": metrics[
                    "quantized_transformed_vertex_error_max"
                ],
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    export(parse_arguments())
